# Brownie configuration file
# https://eth-brownie.readthedocs.io/en/latest/config.html
network:
    default: development # the default network that brownie connects to
    settings:
        gas_limit: false
        gas_price: false
        reverting_tx_gas_limit: false  # if false, reverting tx's will raise without broadcasting
pytest:
    # these settings replace the defaults when running pytest
    gas_limit: 6721975
    default_contract_owner: false
    reverting_tx_gas_limit: 6721975
    revert_traceback: false
compiler:
    solc:
        version: 0.5.4
        evm_version: "byzantium"
        optimize: true
        runs: 200
        minify_source: false
        remappings:
          - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.0.1"
colors:
    key:
    value: bright blue
    callable: bright cyan
    module: bright blue
    contract: bright magenta
    contract_method: bright magenta
    string: bright magenta
    dull: dark white
    error: bright red
    success: bright green
    pending: bright yellow
